---
- hosts: elevate
  vars:
    project_path: /opt/frontend/sgdashboard
    vault_token_path: /opt/backend/deployment/.token
    pm2_config_url: "{{ vaultAddress }}sgdashboardPm2Config"

  tasks:

    - name: Read Vault token from file
      slurp:
        src: "{{ vault_token_path }}"
      register: slurpfile

    - name: Decode Vault token
      set_fact:
        vault_token: "{{ slurpfile['content'] | b64decode }}"

    - name: Ensure project directory exists
      file:
        path: "{{ project_path }}"
        state: directory
        mode: '0755'

    - name: Clone the repo
      git:
        repo: https://github.com/Vinod-V3/sgdashboard
        dest: "{{project_path}}"
        version: "{{gitBranch}}"
        force: yes

    - name: Install npm packages
      shell: npm install --force
      args:
        chdir: "{{ project_path }}"

    - name: Fetch pm2 config from vault
      shell: >
        curl --location --request GET '{{ pm2_config_url }}'
        --header 'X-Vault-Token: {{ vault_token }}' |
        jq '.data' > pm2.config.json
      args:
        chdir: "{{ project_path }}"

    - name: Remove dist folder
      file:
        path: "{{ project_path }}/dist"
        state: absent

    - name: Build Angular portal
      shell: ng build --configuration production
      args:
        chdir: "{{ project_path }}"

    - name: Start portal using PM2
      shell: pm2 start pm2.config.json
      args:
        chdir: "{{ project_path }}"