---
- hosts: elevate
  vars:
    project_path: /opt/frontend/sgdashboard
    root_path: /opt/frontend
  tasks:
    - name: Slurp host file
      slurp:
        src: "/opt/backend/deployment/.token"
      register: slurpfile
    - name: Run vault credentials
      shell: "curl --location --request GET '{{ vaultAddress }}sg-dashboard' --header 'X-Vault-Token: {{ slurpfile['content'] | b64decode }}' | jq '.data' > '{{root_path}}/data2.json'"
      register: vaultCurl
    - name: Ensure project directory exists
      file:
        path: "{{ project_path }}"
        state: directory
        mode: '0755'
    - name: Change directory
      shell: cd {{project_path}}
    - name: Fetch the latest code
      git:
        repo: https://github.com/Vinod-V3/sgdashboard
        dest: "{{project_path}}"
        version: "{{gitBranch}}"
        force: yes
    - name: Update npm
      shell: cd {{project_path}} && npm i --force
    - name: Set permission
      shell: chmod 744 {{ project_path }}/src/scripts/json2env.sh
    - name: Generate .env
      shell: cat {{root_path}}/data2.json | jq '.data' > {{ project_path }}/environments/environment.ts && sed -i '1s/^/export const environment = \n/' {{ project_path }}/environments/environment.ts
      register: envConfig
    - debug: msg=" cred {{ envConfig }} "
    - name: Change directory
      shell: chdir {{project_path}}
    - name: Change directory
      shell: cd {{project_path}}
    - name: Fetch pm2 config file
      shell: "curl --location --request GET '{{ vaultAddress }}sgdashboardPm2Config' --header 'X-Vault-Token: {{ slurpfile['content'] | b64decode }}' | jq '.data.data' > '{{ project_path }}/pm2.config.json'"
      register: pm2
    - name: Remove dist folder
      shell: rm -rf dist
    - name: Build angular portal
      shell: cd {{project_path}} && ng build --configuration production
    - name: Start pm2
      shell: cd {{project_path}} && pm2 start pm2.config.json